import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import type { ToolDeps } from "./deps.js";

export function registerGetReportWeakSubjectsTool(server: McpServer, deps: ToolDeps) {
  server.tool(
    "get_report_weak_subjects",
    "Get weak-question context from a completed interview report. Use this to write strong answers (max 3 lines each), then call generate_report_ui.",
    {
      sessionId: z.string().optional().describe("Completed session ID (preferred when known)"),
      topic: z.string().optional().describe("Topic name; when provided, uses the most recent ended session for this topic"),
      weakScoreThreshold: z.number().int().min(1).max(5).default(3)
        .describe("Treat scores <= this threshold as weak"),
      maxSubjects: z.number().int().min(1).max(10).default(5)
        .describe("Maximum number of weak subjects to return"),
    },
    async ({ sessionId, topic, weakScoreThreshold, maxSubjects }) => {
      if (!sessionId && !topic) {
        return deps.stateError("Provide either sessionId or topic.");
      }

      const sessions = deps.loadSessions();
      const session = sessionId
        ? sessions[sessionId]
        : deps.pickSessionByTopic(sessions, topic!);

      if (!session) {
        return deps.stateError(sessionId
          ? `Session '${sessionId}' not found.`
          : `No ended session found for topic '${topic}'.`);
      }
      if (session.state !== "ENDED") {
        return deps.stateError(`Session '${session.id}' is not ended yet.`);
      }
      if (session.evaluations.length === 0) {
        return deps.stateError(`Session '${session.id}' has no evaluations to analyze.`);
      }

      const allQuestions = deps.buildFullQuestionContext(session, weakScoreThreshold);
      const weakQuestionNumbers = new Set(
        deps.extractWeakSubjects(session, weakScoreThreshold, maxSubjects).map((w) => w.questionIndex + 1)
      );
      const weakQuestions = allQuestions.filter((q) => weakQuestionNumbers.has(q.questionNumber));

      return {
        content: [{
          type: "text" as const,
          text: JSON.stringify({
            sessionId: session.id,
            topic: session.topic,
            avgScore: deps.calcAvgScore(session.evaluations),
            weakScoreThreshold,
            questions: weakQuestions.map((q) => ({
              questionNumber: q.questionNumber,
              subject: q.subject,
              question: q.question,
              candidateAnswer: q.candidateAnswer,
              interviewerFeedback: q.interviewerFeedback,
              score: q.score,
              strongAnswer: q.strongAnswer ?? "TODO: max 3 lines",
            })),
            requiresFollowUpCall: true,
            followUpStatus: "PENDING_GENERATE_REPORT_UI",
            followUpReason: "The UI file is not generated by this tool. generate_report_ui must be called next.",
            nextTool: "generate_report_ui",
            nextCall: {
              tool: "generate_report_ui",
              arguments: {
                sessionId: session.id,
                title: `Weak Questions Report — ${session.topic}`,
                questions: weakQuestions.map((q) => ({
                  questionNumber: q.questionNumber,
                  subject: q.subject,
                  question: q.question,
                  candidateAnswer: q.candidateAnswer,
                  interviewerFeedback: q.interviewerFeedback,
                  score: q.score,
                  strongAnswer: q.strongAnswer ?? "TODO: max 3 lines",
                })),
              },
            },
            instruction:
              "Mandatory next step: replace each TODO strongAnswer (maximum 3 lines), then immediately call nextCall.tool with nextCall.arguments in the same workflow.",
          }),
        }],
      };
    }
  );
}
