import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import type { ToolDeps } from "./deps.js";

export function registerGetReportFullContextTool(server: McpServer, deps: ToolDeps) {
  server.tool(
    "get_report_full_context",
    "Get full report context (all evaluated questions, candidate answers, interviewer feedback, and weak markers). Use this only when a full report UI is needed.",
    {
      sessionId: z.string().optional().describe("Completed session ID (preferred when known)"),
      topic: z.string().optional().describe("Topic name; when provided, uses the most recent ended session for this topic"),
      weakScoreThreshold: z.number().int().min(1).max(5).default(3)
        .describe("Mark questions with score <= threshold as weak"),
    },
    async ({ sessionId, topic, weakScoreThreshold }) => {
      if (!sessionId && !topic) {
        return deps.stateError("Provide either sessionId or topic.");
      }

      const sessions = deps.loadSessions();
      const session = sessionId
        ? sessions[sessionId]
        : deps.pickSessionByTopic(sessions, topic!);

      if (!session) {
        return deps.stateError(sessionId
          ? `Session '${sessionId}' not found.`
          : `No ended session found for topic '${topic}'.`);
      }
      if (session.state !== "ENDED") {
        return deps.stateError(`Session '${session.id}' is not ended yet.`);
      }
      if (session.evaluations.length === 0) {
        return deps.stateError(`Session '${session.id}' has no evaluations to analyze.`);
      }

      const questions = deps.buildFullQuestionContext(session, weakScoreThreshold);
      const weakSubjects = deps.extractWeakSubjects(session, weakScoreThreshold, 10).map((w) => ({
        questionNumber: w.questionIndex + 1,
        subject: w.subject,
        score: w.score,
        gapSummary: w.gapSummary,
      }));

      return {
        content: [{
          type: "text" as const,
          text: JSON.stringify({
            sessionId: session.id,
            topic: session.topic,
            summary: session.summary ?? deps.buildSummary(session),
            avgScore: deps.calcAvgScore(session.evaluations),
            weakScoreThreshold,
            questions: questions.map((q) => ({
              questionNumber: q.questionNumber,
              subject: q.subject,
              question: q.question,
              candidateAnswer: q.candidateAnswer,
              interviewerFeedback: q.interviewerFeedback,
              score: q.score,
              strongAnswer: "TODO: max 3 lines",
            })),
            weakSubjects,
            requiresFollowUpCall: true,
            followUpStatus: "PENDING_GENERATE_REPORT_UI",
            followUpReason: "The UI file is not generated by this tool. generate_report_ui must be called next.",
            nextTool: "generate_report_ui",
            nextCall: {
              tool: "generate_report_ui",
              arguments: {
                sessionId: session.id,
                title: `Full Report — ${session.topic}`,
                questions: questions.map((q) => ({
                  questionNumber: q.questionNumber,
                  subject: q.subject,
                  question: q.question,
                  candidateAnswer: q.candidateAnswer,
                  interviewerFeedback: q.interviewerFeedback,
                  score: q.score,
                  strongAnswer: "TODO: max 3 lines",
                })),
              },
            },
            instruction:
              "Mandatory next step: replace each TODO strongAnswer (maximum 3 lines), then immediately call nextCall.tool with nextCall.arguments in the same workflow.",
          }),
        }],
      };
    }
  );
}
