export type InterviewState =
  | "ASK_QUESTION"
  | "WAIT_FOR_ANSWER"
  | "EVALUATE_ANSWER"
  | "FOLLOW_UP"
  | "ENDED";

export interface Message {
  role: "interviewer" | "candidate";
  content: string;
  timestamp: string;
}

export interface Evaluation {
  questionIndex: number;
  question: string;
  answer: string;
  score: number;          // 1–5
  feedback: string;
  needsFollowUp: boolean;
  followUpQuestion?: string;
  deeperDive?: string;    // Markdown bullets: "where to go deeper" — generated at interview end
}

export interface Session {
  id: string;
  topic: string;
  state: InterviewState;
  currentQuestionIndex: number;
  questions: string[];
  messages: Message[];
  evaluations: Evaluation[];
  summary?: string;
  concepts?: Concept[];
  createdAt: string;
  endedAt?: string;
  /** "file" when questions/concepts came from data/knowledge/, "ai" when generated by the AI provider */
  knowledgeSource: "file" | "ai";
}

export interface Concept {
  word: string;
  cluster: string;
}

export interface GraphNode {
  id: string;
  label: string;
  clusters: string[];
}

export interface GraphEdge {
  source: string;
  target: string;
  weight: number;
}

export interface KnowledgeGraph {
  nodes: GraphNode[];
  edges: GraphEdge[];
  sessions: string[];
}

export interface EvaluationResult {
  score: number;           // 1–5
  feedback: string;        // one sentence, specific and actionable
  needsFollowUp: boolean;  // true when the answer needs probing
  followUpQuestion?: string;
  deeperDive?: string;     // markdown bullets returned together with the evaluation — no extra API call
}
