spring.application.name=api-exercise

server.port=8081
server.tomcat.threads.max=2
server.tomcat.accept-count=2
server.tomcat.connection-timeout=5s

logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
