// ─────────────────────────────────────────────────────────────────────────────
// @mock-interview/shared — single source of truth for all domain types
//
// Used by: interview-mcp  report-mcp  ui
// Never duplicate these — import from this package instead.
// ─────────────────────────────────────────────────────────────────────────────

// ── Interview state machine ───────────────────────────────────────────────────

export type InterviewState =
  | 'ASK_QUESTION'
  | 'WAIT_FOR_ANSWER'
  | 'EVALUATE_ANSWER'
  | 'FOLLOW_UP'
  | 'ENDED'

export type SessionKind = 'interview' | 'study' | 'drill'
export type StudyCategory = 'topic' | 'algorithm'
export type InterviewType = 'design' | 'code'

// ── Session data ──────────────────────────────────────────────────────────────

export interface Message {
  role: 'interviewer' | 'candidate'
  content: string
  timestamp: string
}

export interface Evaluation {
  questionIndex: number
  question: string
  answer: string
  strongAnswer?: string
  score: number           // 1–5
  feedback: string
  needsFollowUp: boolean
  followUpQuestion?: string
  deeperDive?: string     // markdown bullets: "where to go deeper"
}

export interface Concept {
  word: string
  cluster: string
}

export interface Session {
  id: string
  topic: string
  /** Interview type — 'design' (default) or 'code' (future). Absent on legacy sessions → treat as 'design'. */
  interviewType?: InterviewType
  sessionKind?: SessionKind
  studyCategory?: StudyCategory
  sourcePath?: string
  sourceType?: 'markdown' | 'java'
  seeded?: boolean
  /** Raw content/spec passed to start_scoped_interview — used as rubric context during evaluation */
  customContent?: string
  /** The interview angle for a scoped session, e.g. "robustness, reliability, and extensibility" */
  focusArea?: string
  state: InterviewState
  currentQuestionIndex: number
  questions: string[]
  messages: Message[]
  evaluations: Evaluation[]
  summary?: string
  concepts?: Concept[]
  createdAt: string
  endedAt?: string
  /** "file" = questions came from data/knowledge/, "ai" = generated by AI provider */
  knowledgeSource: 'file' | 'ai'
}

// ── Knowledge graph ───────────────────────────────────────────────────────────

export interface GraphNode {
  id: string
  label: string
  clusters: string[]
}

export interface GraphEdge {
  source: string
  target: string
  weight: number
}

export interface KnowledgeGraph {
  nodes: GraphNode[]
  edges: GraphEdge[]
  sessions: string[]
}

// ── AI provider ───────────────────────────────────────────────────────────────

export interface EvaluationResult {
  score: number           // 1–5
  feedback: string        // one sentence, specific and actionable
  needsFollowUp: boolean
  followUpQuestion?: string
  deeperDive?: string
}

// ── Flashcards ────────────────────────────────────────────────────────────────

export type FlashcardDifficulty = 'easy' | 'medium' | 'hard'

export interface Flashcard {
  id: string
  /** The question or concept prompt shown to the user */
  front: string
  /** Rich explanation: correct answer, key points, common pitfalls */
  back: string
  topic: string
  tags: string[]
  difficulty: FlashcardDifficulty
  /** Where the card came from */
  source: {
    sessionId: string
    questionIndex: number
    originalScore: number   // the score that triggered creation (< 4)
  }
  createdAt: string

  // ── Spaced repetition (SM-2) ────────────────────────────────────────────────
  /** ISO date string — when the card is next due for review */
  dueDate: string
  /** Current interval in days between reviews */
  interval: number
  /** SM-2 ease factor — starts at 2.5, adjusted by review rating */
  easeFactor: number
  /** How many times reviewed successfully in a row */
  repetitions: number
  lastReviewedAt?: string
}

/** Rating passed to review_flashcard — mirrors SM-2 quality 1–4 */
export type ReviewRating = 1 | 2 | 3 | 4

export interface FlashcardReviewResult {
  cardId: string
  rating: ReviewRating
  nextDueDate: string
  nextInterval: number
  nextEaseFactor: number
}

// ── Mistake log ───────────────────────────────────────────────────────────────

export interface Mistake {
  id: string
  /** What went wrong */
  mistake: string
  /** When / in what context it happens */
  pattern: string
  /** The correct approach or fix */
  fix: string
  /** Optional topic tag (e.g. "Java Thread States") */
  topic?: string
  createdAt: string
}

// ── HTTP API responses (used by ui) ───────────────────────────────────────────

export interface ReportMeta {
  id: string
  topic: string
  avgScore: string
  date: string | null
  file: string
}
