// ─────────────────────────────────────────────────────────────────────────────
// @mock-interview/shared — single source of truth for all domain types
//
// Used by: interview-mcp  report-mcp  ui
// Never duplicate these — import from this package instead.
// ─────────────────────────────────────────────────────────────────────────────

// ── Interview state machine ───────────────────────────────────────────────────

export type InterviewState =
  | 'ASK_QUESTION'
  | 'WAIT_FOR_ANSWER'
  | 'EVALUATE_ANSWER'
  | 'FOLLOW_UP'
  | 'ENDED'

// ── Session data ──────────────────────────────────────────────────────────────

export interface Message {
  role: 'interviewer' | 'candidate'
  content: string
  timestamp: string
}

export interface Evaluation {
  questionIndex: number
  question: string
  answer: string
  score: number           // 1–5
  feedback: string
  needsFollowUp: boolean
  followUpQuestion?: string
  deeperDive?: string     // markdown bullets: "where to go deeper"
}

export interface Concept {
  word: string
  cluster: string
}

export interface Session {
  id: string
  topic: string
  state: InterviewState
  currentQuestionIndex: number
  questions: string[]
  messages: Message[]
  evaluations: Evaluation[]
  summary?: string
  concepts?: Concept[]
  createdAt: string
  endedAt?: string
  /** "file" = questions came from data/knowledge/, "ai" = generated by AI provider */
  knowledgeSource: 'file' | 'ai'
}

// ── Knowledge graph ───────────────────────────────────────────────────────────

export interface GraphNode {
  id: string
  label: string
  clusters: string[]
}

export interface GraphEdge {
  source: string
  target: string
  weight: number
}

export interface KnowledgeGraph {
  nodes: GraphNode[]
  edges: GraphEdge[]
  sessions: string[]
}

// ── AI provider ───────────────────────────────────────────────────────────────

export interface EvaluationResult {
  score: number           // 1–5
  feedback: string        // one sentence, specific and actionable
  needsFollowUp: boolean
  followUpQuestion?: string
  deeperDive?: string
}

// ── HTTP API responses (used by ui) ───────────────────────────────────────────

export interface ReportMeta {
  id: string
  topic: string
  avgScore: string
  date: string | null
  file: string
}
