import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { ToolDeps } from "./deps.js";
import { registerServerStatusTool } from "./serverStatus.js";
import { registerHelpTools } from "./helpTools.js";
import { registerStartInterviewTool } from "./startInterview.js";
import { registerAskQuestionTool } from "./askQuestion.js";
import { registerSubmitAnswerTool } from "./submitAnswer.js";
import { registerEvaluateAnswerTool } from "./evaluateAnswer.js";
import { registerAskFollowupTool } from "./askFollowup.js";
import { registerNextQuestionTool } from "./nextQuestion.js";
import { registerEndInterviewTool } from "./endInterview.js";
import { registerGetSessionTool } from "./getSession.js";
import { registerListSessionsTool } from "./listSessions.js";
import { registerListTopicsTool } from "./listTopics.js";
import { registerGetDueFlashcardsTool } from "./getDueFlashcards.js";
import { registerReviewFlashcardTool } from "./reviewFlashcard.js";
import { registerCreateFlashcardTool } from "./createFlashcard.js";
import { registerStartScopedInterviewTool } from "./startScopedInterview.js";
import { registerLogMistakeTool } from "./logMistake.js";
import { registerListMistakesTool } from "./listMistakes.js";
import { registerStartDrillTool } from "./startDrill.js";
import { registerAddSkillTool } from "./addSkill.js";
import { registerListSkillsTool } from "./listSkills.js";
import { registerUpdateSkillTool } from "./updateSkill.js";
import { registerPracticeMicroSkillTool } from "./practiceMicroSkill.js";
import { registerCreateExerciseTool } from "./createExercise.js";
import { registerListExercisesTool } from "./listExercises.js";
import { registerBuildScopeTool } from "./buildScope.js";

export function registerAllTools(server: McpServer, deps: ToolDeps) {
  registerServerStatusTool(server, deps);
  registerHelpTools(server, deps);
  registerStartInterviewTool(server, deps);
  registerStartScopedInterviewTool(server, deps);
  registerAskQuestionTool(server, deps);
  registerSubmitAnswerTool(server, deps);
  registerEvaluateAnswerTool(server, deps);
  registerAskFollowupTool(server, deps);
  registerNextQuestionTool(server, deps);
  registerEndInterviewTool(server, deps);
  registerGetSessionTool(server, deps);
  registerListSessionsTool(server, deps);
  registerListTopicsTool(server, deps);
  registerGetDueFlashcardsTool(server, deps);
  registerCreateFlashcardTool(server, deps);
  registerReviewFlashcardTool(server, deps);
  registerLogMistakeTool(server, deps);
  registerListMistakesTool(server, deps);
  registerStartDrillTool(server, deps);
  registerAddSkillTool(server, deps);
  registerListSkillsTool(server, deps);
  registerUpdateSkillTool(server, deps);
  registerPracticeMicroSkillTool(server, deps);
  registerCreateExerciseTool(server, deps);
  registerListExercisesTool(server, deps);
  registerBuildScopeTool(server, deps);
}
